function [featureVectors, labels] = getFeatureVectors(EMG, segmentationMask, label, options)
% This function extracts several feature vectors given an EMG acompanied of
% its mask generated by the manual segmentation of the region that contains
% the contraction of the gesture performed. 
%
% Marco E. Benalcázar, Ph.D.
% Artificial Intelligence and Computer Vision Research Lab
% Escuela Politécnica Nacional, Quito - Ecuador
% marco.benalcazar@epn.edu.ec

% Parameters for the sliding window
windowSize = options.windowSize;
stride = options.stride;

% Scanning the EMG, from left to right
featureVectors = [];
labels = [];
for t = 1:stride:(size(EMG,1)-windowSize)
    windowObservation = EMG(t:(t+windowSize-1),:);
    featureVectors = [featureVectors; observationToFeatureVector(windowObservation)];
    if ~isempty(segmentationMask) && ~isempty(label) 
        labels = [labels; label*max( segmentationMask(t:(t+windowSize-1)) )];
    end
end
return